### PR TITLE
Implement `PrimaryKey` for `AssetInfo`

### PR DESCRIPTION
**Pull request by CyberHoward**
See #20 for discussion on the matter. 

I can add tests if there's agreement on the implementation.

### CODE REVIEW

**Comment by larry0x** [comment]
@CyberHoward I think you should implement `PrimaryKey` for `&AssetInfo` instead of for `AssetInfo`. This allows you to avoid to clone the asset info and save gas in many cases. I'm going to change the implementation if you're not against it.

**Comment by CyberHoward** [comment]
Sure, tho it might cause issues in the `KeyDeserialize` trait.

**Comment by larry0x** [comment]
@CyberHoward In [this commit](https://github.com/mars-protocol/cw-asset/commit/b1ba69fe611a4356c09027f249fa256bc784c414) you see I avoid all cloning and have no problem with `KeyDeserialize`.

In short, the key in the map is `&AssetInfo`, but when deserializing we deserializing to an owned `AssetInfo`.

**Comment by larry0x** [comment]
@CyberHoward I create a pre-release including all the changes I've made today. Let me know if this works for you. If yes I will make a formal release: https://github.com/mars-protocol/cw-asset/releases/tag/v3.0.0-rc1

**Pull request merged**
