### PR TITLE
Add `#[non_exhaustive]` tag on `AssetInfoBase`

### PR DESCRIPTION
**Pull request by y-pakorn**
This should solve #14

### CODE REVIEW

**Comment by larry0x** [comment]
thanks! good suggestion.

this being said, can you revert all the unrelated styling changes such as this:

```diff
- return Err(StdError::generic_err(
-     format!("invalid asset info format `{}`; must be in format `native:{{denom}}`", s)
- ));
+ return Err(StdError::generic_err(format!(
+    "invalid asset info format `{}`; must be in format `native:{{denom}}`",
+    s
+ )));
```

and do not use `rustfmt`? i find code stylized by rustfmt to be very ugly. instead i handcraft the styling of all my code based on my preference.

**Comment by y-pakorn** [comment]
> thanks! good suggestion.
> 
> this being said, can you revert all the unrelated styling changes such as this:
> 
> ```diff
> - return Err(StdError::generic_err(
> -     format!("invalid asset info format `{}`; must be in format `native:{{denom}}`", s)
> - ));
> + return Err(StdError::generic_err(format!(
> +    "invalid asset info format `{}`; must be in format `native:{{denom}}`",
> +    s
> + )));
> ```
> 
> and do not use `rustfmt`? i find code stylized by rustfmt to be very ugly. instead i handcraft the styling of all my code based on my preference.

Haha sure!

**Comment by larry0x** [comment]
thanks, i'm merging now. i'll do some testing shortly and then tag a release

**Comment by apollo-sturdy** [comment]
@larry0x This change seems to have broken all our codebases as it now requires our match statements to include _ which it previously did not. Should this change have been added in a new major version instead?

**Comment by larry0x** [comment]
> @larry0x This change seems to have broken all our codebases as it now requires our match statements to include _ which it previously did not. Should this change have been added in a new major version instead?

This comes as surprise to me: i thought i should do the opposite, that is, allowing you to not have to include _ 

in this case, in deed this is a breaking change and should have used a major version bump.

**Comment by apollo-sturdy** [comment]
> > @larry0x This change seems to have broken all our codebases as it now requires our match statements to include _ which it previously did not. Should this change have been added in a new major version instead?
> 
> This comes as surprise to me: i thought it would do the opposite, that is, allowing you to not have to include _
> 
> in this case, in deed this is a breaking change and should have used a major version bump.

The previous behaviour was allowing not to include _ and instead just matching all enum variants, which we were doing. After updating to 2.3.0 it requires us to include _ even if we are already matching all current enum variants.

**Comment by y-pakorn** [comment]
> > > @larry0x This change seems to have broken all our codebases as it now requires our match statements to include _ which it previously did not. Should this change have been added in a new major version instead?
> > 
> > 
> > This comes as surprise to me: i thought it would do the opposite, that is, allowing you to not have to include _
> > in this case, in deed this is a breaking change and should have used a major version bump.
> 
> The previous behaviour was allowing not to include _ and instead just matching all enum variants, which we were doing. After updating to 2.3.0 it requires us to include _ even if we are already matching all current enum variants.

Thats the expected behavior, it will always assume that the guard could fail. So when new enum variant has been added your package will not break.

The simplest workaround is to add '_ => unreachable!()' if you are sure that you handle all the other cases properly.

**Pull request merged**
